name: network
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  dio: ^5.3.2
  retrofit: ^4.0.1
  json_annotation: ^4.8.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.8
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
